//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateDatabase.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class dükkan
    {
        public dükkan()
        {
            this.temsilci = new HashSet<temsilci>();
        }
    
        public int dükkan_id { get; set; }
        public string dükkan_adı { get; set; }
        public string dükkan_telno { get; set; }
    
        public virtual ICollection<temsilci> temsilci { get; set; }
    }
}
