//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateDatabase.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class kiracı
    {
        public kiracı()
        {
            this.kira_kayıt = new HashSet<kira_kayıt>();
        }
    
        public int kiracı_id { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string telno { get; set; }
    
        public virtual ICollection<kira_kayıt> kira_kayıt { get; set; }
    }
}
