//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateDatabase.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class kira_kayıt
    {
        public int kira_kayıt_id { get; set; }
        public int ev_sahibi_id { get; set; }
        public int kiralık_ev_id { get; set; }
        public int temsilci_id { get; set; }
        public int kiracı_id { get; set; }
        public int kiralama_fiyatı { get; set; }
    
        public virtual ev_sahibi ev_sahibi { get; set; }
        public virtual kiracı kiracı { get; set; }
        public virtual kiralık_ev kiralık_ev { get; set; }
        public virtual temsilci temsilci { get; set; }
    }
}
