//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateDatabase.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class kiralık_ev
    {
        public kiralık_ev()
        {
            this.kira_kayıt = new HashSet<kira_kayıt>();
        }
    
        public int kiralık_ev_id { get; set; }
        public string sokak { get; set; }
        public int kapı_no { get; set; }
        public string ada_parsel { get; set; }
        public int kat_sayısı { get; set; }
        public int bulunduğu_kat { get; set; }
        public int oda_sayısı { get; set; }
        public int salon_sayısı { get; set; }
        public int fiyat { get; set; }
        public int kiracı_id { get; set; }
        public int ev_sahibi_id { get; set; }
        public int mahalle_id { get; set; }
        public int temsilci_id { get; set; }
    
        public virtual ev_sahibi ev_sahibi { get; set; }
        public virtual ICollection<kira_kayıt> kira_kayıt { get; set; }
        public virtual mahalle mahalle { get; set; }
        public virtual temsilci temsilci { get; set; }
    }
}
