//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateDatabase.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class temsilci
    {
        public temsilci()
        {
            this.kira_kayıt = new HashSet<kira_kayıt>();
            this.kiralık_ev = new HashSet<kiralık_ev>();
            this.satılık_ev = new HashSet<satılık_ev>();
            this.satış_kaydı = new HashSet<satış_kaydı>();
        }
    
        public int temsilci_id { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string tel_no { get; set; }
        public int dükkan_id { get; set; }
    
        public virtual dükkan dükkan { get; set; }
        public virtual ICollection<kira_kayıt> kira_kayıt { get; set; }
        public virtual ICollection<kiralık_ev> kiralık_ev { get; set; }
        public virtual ICollection<satılık_ev> satılık_ev { get; set; }
        public virtual ICollection<satış_kaydı> satış_kaydı { get; set; }
    }
}
