//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateDatabase.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class şehir
    {
        public şehir()
        {
            this.mahalle = new HashSet<mahalle>();
        }
    
        public int şehir_id { get; set; }
        public string şehir_ismi { get; set; }
    
        public virtual ICollection<mahalle> mahalle { get; set; }
    }
}
